SHELL := /usr/bin/bash

.PHONY: fast ultimate full extra health bench status
fast:
	bash /workspace/scripts/fast_env_boost.sh

ultimate:
	bash /workspace/scripts/ultimate_speed.sh

full:
	bash /workspace/scripts/full_boost.sh

extra:
	bash /workspace/scripts/extra_speed_boost.sh

health:
	bash /workspace/scripts/env_health_check.sh

bench:
	bash /workspace/scripts/benchmark_team_speed.sh

status:
	bash /workspace/scripts/status.sh